# NumPy


- 📌 What is NumPy?

NumPy stands for Numerical Python.
It is a library used for fast mathematical and array operations.

In [1]:
import numpy as np

In [2]:
lst = [1,2,3,4,5]

arr = np.array(lst)

type(arr)

numpy.ndarray

In [3]:
print(arr)

[1 2 3 4 5]


In [12]:
sz = arr.size
maxm = arr.max()
minm = arr.min()
shp = arr.shape
mn = arr.mean()

print(sz)
print(maxm)
print(minm)
print(shp)
print(mn)

5
5
1
(5,)
3.0


In [14]:
lst1 = [1,2,3,4,5]
lst2 = [6,7,8,9,10]
lst3 = [11,12,13,14,15]

arr = np.array([lst1,lst2,lst3])

In [15]:
print(arr)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


In [18]:
print(arr.size)
print(arr.shape)

15
(3, 5)


In [19]:
arr.reshape(5,3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15]])

In [22]:
#arr.reshape(6,4)    # cannot do because 6x4 = 24 that is > 3x5 = 15(of original)

In [122]:
arr = np.array([1,2,3,4,5])

type(arr)

numpy.ndarray

In [25]:
print(arr[2])

3


In [126]:
print(arr[:-1])
print(arr[::-1])     #start from last and gap of 1 means continous
print(arr[::-2])     #start from last and gap of 2 

[1 2 3 4]
[5 4 3 2 1]
[5 3 1]


In [27]:
lst1 = [1,2,3,4,5]
lst2 = [6,7,8,9,10]
lst3 = [11,12,13,14,15]

arr = np.array([lst1,lst2,lst3])

In [28]:
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [29]:
arr[0]

array([1, 2, 3, 4, 5])

In [35]:
arr[0:2,0:4]     # arr[startROW : endROW , startCOLUMN : endCOLUMN]

array([[1, 2, 3, 4],
       [6, 7, 8, 9]])

In [34]:
arr[:3,2:]

array([[ 3,  4,  5],
       [ 8,  9, 10],
       [13, 14, 15]])

In [36]:
arr[1:,2:4]

array([[ 8,  9],
       [13, 14]])

In [37]:
arr[1:2,1:4]

array([[7, 8, 9]])

In [45]:
arr = np.arange(0,20,2)     #(Start , Stop , Gap)

In [46]:
arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [47]:
arr = np.arange(3,9)

arr

array([3, 4, 5, 6, 7, 8])

In [53]:
arr = np.linspace(0,10,num = 20)   #(Start , Stop , Value between these numbers (Fractionalize between range with equal space))

arr

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

In [60]:
arr = np.array([1,2,3,4,5])

arr1 = arr

arr[2:] = 100

print(arr)      # Reference type copy makwe change in both arrays
print(arr1)

[  1   2 100 100 100]
[  1   2 100 100 100]


In [59]:
arr1 = arr.copy()
arr1[2:] = 500

print(arr)    # Non-reference type copy only change in duplicate array
print(arr1)

[  1   2 100 100 100]
[  1   2 500 500 500]


- Some condtitions are

In [69]:
arr = np.array([1,2,3,4,5,6,7,8,9])

print(arr<2)
print(arr*2)

print(arr[arr<5])

[ True False False False False False False False False]
[ 2  4  6  8 10 12 14 16 18]
[1 2 3 4]


In [70]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [77]:
arr = np.ones(7)
print(arr)

arr = np.ones(4,dtype = int)
print(arr)

arr = np.ones(5,dtype = float)
print(arr)

[1. 1. 1. 1. 1. 1. 1.]
[1 1 1 1]
[1. 1. 1. 1. 1.]


In [78]:
arr = np.random.rand(3,3)
print(arr)

[[0.72323492 0.91011849 0.94162318]
 [0.65213326 0.66900118 0.62555976]
 [0.1568078  0.64668442 0.71629458]]


In [159]:
arr = np.random.randn(3,3)     # (shape)   mean = 0 ,  SD = 1
print(arr)

[[-0.09266741  0.8385147   0.72796854]
 [ 0.84366542  0.83811654  0.62217467]
 [ 1.16091253 -0.11899824  0.40074012]]


In [160]:
arr = np.random.randint(0,100,10)   #(start , end , total number)
print(arr.reshape(5,2))

[[59 68]
 [67 47]
 [59 93]
 [81 74]
 [ 9 11]]


In [91]:
arr = np.random.random_sample((2,4))     # (row , column)
print(arr)

[[0.56254782 0.63872667 0.67411544 0.04965645]
 [0.12909548 0.16593323 0.26861601 0.08615003]]


In [101]:
arr = np.array([1,2,3,4,5])
arr1 = np.array([0,6,7,8,9])

x1 = np.add(arr,arr1)
print(x1)


[ 1  8 10 12 14]


In [105]:
x = np.concatenate((arr,arr1))
print(x)

[1 2 3 4 5 0 6 7 8 9]


In [106]:
x = np.concat((arr,arr1))
print(x)

[1 2 3 4 5 0 6 7 8 9]


In [109]:
x = np.cumprod(arr)
print(x)

[  1   2   6  24 120]


In [110]:
x = np.cumulative_prod(arr)
print(x)

[  1   2   6  24 120]


In [112]:
arr = np.array([1,2,3,4,5,6,7,8,9])

x = np.delete(arr,4)   # Element at index 4 got deleted
print(x)

[1 2 3 4 6 7 8 9]


In [114]:
arr = np.array([1,2,3,4,5,6,7,8,9])

x = np.delete(arr,[1,3,5])   # Element at index [1,3,5] got deleted
print(x)

[1 3 5 7 8 9]


In [118]:
lst1 = [1,2,3,4,5]
lst2 = [6,7,8,9,10]
lst3 = [11,12,13,14,15]

arr = np.array([lst1,lst2,lst3])

In [120]:
x = np.delete(arr,np.s_[::5])

print(x)

[ 2  3  4  5  7  8  9 10 12 13 14 15]


In [148]:
arr = np.arange(1,61,1)
arr11 = np.arange(1,31,1)
arr44 = np.arange(1,61,1)

print(arr)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49 50 51 52 53 54 55 56 57 58 59 60]


In [149]:
arr2 = arr11.reshape(5,6)           # 2 dimensions
print(arr2)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]]


In [150]:
arr3 = arr11.reshape(2,3,5)       # 3 dimensions
print(arr3)   

[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]
  [11 12 13 14 15]]

 [[16 17 18 19 20]
  [21 22 23 24 25]
  [26 27 28 29 30]]]


In [151]:
arr4 = arr44.reshape(4,1,3,5)   # 4 dimensions
print(arr4)

[[[[ 1  2  3  4  5]
   [ 6  7  8  9 10]
   [11 12 13 14 15]]]


 [[[16 17 18 19 20]
   [21 22 23 24 25]
   [26 27 28 29 30]]]


 [[[31 32 33 34 35]
   [36 37 38 39 40]
   [41 42 43 44 45]]]


 [[[46 47 48 49 50]
   [51 52 53 54 55]
   [56 57 58 59 60]]]]


#### Matrix Multiplication

In [164]:
lst1 = [-2,-1, 3]
lst2 = [-6 ,-3 ,9]

arr = np.array([lst1,lst2])

arrT = np.transpose(arr)

print(arr)
print(arrT)

mul = np.matmul(arr,arrT)          #Matrix Multiplication
mul1 = np.dot(arr,arrT)            #Matrix Multiplication

print(mul1)
print(mul)

[[-2 -1  3]
 [-6 -3  9]]
[[-2 -6]
 [-1 -3]
 [ 3  9]]
[[ 14  42]
 [ 42 126]]
[[ 14  42]
 [ 42 126]]


## GPT Practice

In [165]:
a = np.array([[1, 2, 3], [4, 5, 6]])

print(a.shape)   # (rows, columns)
print(a.ndim)    # dimensions
print(a.size)    # total elements
print(a.dtype)   # data type

(2, 3)
2
6
int64


In [166]:
np.array([1,2,3, "hello"])  # Converts all to string

array(['1', '2', '3', 'hello'], dtype='<U21')

In [177]:
arr = np.eye(3,dtype = int)      # identity matrix
print(arr)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [181]:
a = np.array([1,4,9] )

print(np.sqrt(a))
print(np.log(a))
print(np.sin(a))

[1. 2. 3.]
[0.         1.38629436 2.19722458]
[ 0.84147098 -0.7568025   0.41211849]


In [182]:
a = np.array([1,2,3,4])

print(np.sum(a))
print(np.mean(a))
print(np.max(a))
print(np.min(a))

10
2.5
4
1


In [195]:
a = np.array([1, 4, 9, 16])

print(np.sqrt(a))
print(np.exp(a))
print(np.log(a))

[1. 2. 3. 4.]
[2.71828183e+00 5.45981500e+01 8.10308393e+03 8.88611052e+06]
[0.         1.38629436 2.19722458 2.77258872]


In [183]:
a = np.array([1,2,3])
b = 2

print(a + b)

[3 4 5]


In [184]:
a = np.array([[1,2,3],[4,5,6]])
b = np.array([1,1,1])

print(a + b)

[[2 3 4]
 [5 6 7]]


In [185]:
lst1 = [1,2,3,4,5]
lst2 = [6,7,8,9,10]
lst3 = [11,12,13,14,15]

arr = np.array([lst1,lst2,lst3])

In [189]:
mn = np.mean(arr,axis=1)
print(mn)

[ 3.  8. 13.]


In [191]:
arr = np.array([1,2,3,4,5,6,7,8,9])

stdz = (arr - np.mean(arr)) / np.std(arr)

print(stdz)

[-1.54919334 -1.161895   -0.77459667 -0.38729833  0.          0.38729833
  0.77459667  1.161895    1.54919334]


In [192]:
arr = np.array([1,2,3,4,5,6,7,8,9])

nmlz = (arr- np.min(arr)) / (np.max(arr) - np.min(arr))

print(nmlz)

[0.    0.125 0.25  0.375 0.5   0.625 0.75  0.875 1.   ]


In [194]:
arr = np.random.randint(1, 100, (5, 5))

# 1. Normalize using Min-Max
# 2. Standardize it
# 3. Do it column-wise (advanced)

nmlz = (arr- np.min(arr)) / (np.max(arr) - np.min(arr))

print(nmlz)

stdz = (arr - np.mean(arr)) / np.std(arr)

print(stdz)



[[0.48913043 0.58695652 0.89130435 1.         0.20652174]
 [0.30434783 0.04347826 0.76086957 0.44565217 0.98913043]
 [0.63043478 0.29347826 0.         0.69565217 0.22826087]
 [0.56521739 0.72826087 0.47826087 0.5        0.51086957]
 [0.23913043 0.75       0.94565217 0.31521739 0.82608696]]
[[-0.17045559  0.17820357  1.26292097  1.65032004 -1.17769318]
 [-0.82903401 -1.75879178  0.79804209 -0.32541522  1.61158014]
 [ 0.3331632  -0.86777392 -1.91375141  0.56560264 -1.10021336]
 [ 0.10072376  0.68182237 -0.2091955  -0.13171568 -0.09297578]
 [-1.06147346  0.75930218  1.45662051 -0.79029411  1.03048153]]


In [196]:
arr = np.array([1,2,3,4,5])

print(np.square(arr))
print(np.pow(arr,3))
print(np.log(arr))

[ 1  4  9 16 25]
[  1   8  27  64 125]
[0.         0.69314718 1.09861229 1.38629436 1.60943791]


In [201]:
a = np.array([1,2,3,4,5,6,7,8,9,0])

print(np.split(a, 2))

[array([1, 2, 3, 4, 5]), array([6, 7, 8, 9, 0])]


## Linear Algebra

In [208]:
lst1 = [4,7]
lst2 = [2,7]

arr = np.array([lst1,lst2])

print(np.linalg.det(arr))
print("\n")
print(np.linalg.inv(arr))
print("\n")
print(np.linalg.eig(arr))

14.000000000000004


[[ 0.5        -0.5       ]
 [-0.14285714  0.28571429]]


EigResult(eigenvalues=array([1.46887113, 9.53112887]), eigenvectors=array([[-0.94041   , -0.78462031],
       [ 0.3400427 , -0.61997658]]))
