# NumPy practice from Book and reading

In [19]:
import numpy as np

In [6]:
arr = np.array([1,2,3,4,5])
print(arr)
print(arr.dtype)

[1 2 3 4 5]
int64


In [8]:
arr = np.array([1,2.5,3,5.8,0])
print(arr)

[1.  2.5 3.  5.8 0. ]


In [9]:
print(arr.dtype)

float64


In [20]:
arr1 = np.empty((1,4))
print(arr1)

[[1.  2.5 3.  5.8]]


In [21]:
arr = np.zeros((3,6))
print(arr)

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


In [38]:
x = np.empty((4,5))
y = np.empty_like(([1,2,3],[4,5,6]))
print(x)
print(y)

[[6.23042070e-307 4.67296746e-307 1.69121096e-306 7.56599807e-307
  3.56022682e-307]
 [8.90100844e-307 7.56587585e-307 1.37961302e-306 1.05699242e-307
  8.01097889e-307]
 [1.78020169e-306 7.56601165e-307 1.02359984e-306 1.33510679e-306
  2.22522597e-306]
 [1.24611674e-306 1.29061821e-306 6.23057349e-307 1.33511562e-306
  6.89805151e-307]]
[[28429264711581742 28429397856419958 32088563961561180]
 [32370073299845220 30399774231756907 14355657611083893]]


In [40]:
idmat = np.identity(5,dtype = int)
print(idmat)

[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]


In [41]:
arr = np.array([1,4.5,-7.8,4.0,3,9.8,-0.6,-5.5])
print(arr)

[ 1.   4.5 -7.8  4.   3.   9.8 -0.6 -5.5]


In [42]:
arr1 = np.astype(arr,int)
print(arr1)

[ 1  4 -7  4  3  9  0 -5]


In [69]:
string = np.array(['1.25','5.8',"3",5])
print(string)

['1.25' '5.8' '3' '5']


In [71]:
nums = string.astype(float).astype(int)   # Convert to float first and then to int
print(nums)

[1 5 3 5]


In [78]:
nums = np.astype(string,float).astype(int)   # Convert to float first and then to int
print(nums)

[1 5 3 5]


In [82]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

print(arr2d)

print(arr2d[0][2])
print(arr2d[1,2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
3
6


In [90]:
 names = np.array(["Bob", "Joe", "Will", "Bob", "Will", "Joe", "Joe"])

 data = np.array([[4, 7], [0, 2], [-5, 6], [0, 0], [1, 2],[-12, -4], [3, 4]])

In [84]:
print(names)
print("\n")
print(data)

['Bob' 'Joe' 'Will' 'Bob' 'Will' 'Joe' 'Joe']


[[  4   7]
 [  0   2]
 [ -5   6]
 [  0   0]
 [  1   2]
 [-12  -4]
 [  3   4]]


In [86]:
names == "Bob"

array([ True, False, False,  True, False, False, False])

In [87]:
data[names == 'Bob']

array([[4, 7],
       [0, 0]])

In [91]:
data[names == "Bob", 1]

array([7, 0])

In [95]:
print(names == "Bob")
print(~(names == "Bob"))

[ True False False  True False False False]
[False  True  True False  True  True  True]


In [96]:
arr = np.empty((8,4))
print(arr)

[[9.48196010e-312 1.06224114e-321 0.00000000e+000 0.00000000e+000]
 [3.56022682e-307 5.02034658e+175 4.75454404e+174 2.17630659e-076]
 [8.82785773e+169 1.25743162e-075 1.09641447e-071 5.50849688e-144]
 [3.59751658e+252 1.46901661e+179 8.37404147e+242 2.59027926e-144]
 [3.80985069e+180 1.14428494e+243 2.59027907e-144 7.79952704e-143]
 [9.30595541e+165 4.01254922e+174 5.70219911e-066 1.74038985e+184]
 [2.59027864e-144 2.59903818e-144 5.88728860e-091 5.65042189e-038]
 [1.79821234e-052 1.11475752e+261 1.16318408e-028 2.59297589e-306]]


In [97]:
for i in range(8):
    arr[i] = i

print(arr)

[[0. 0. 0. 0.]
 [1. 1. 1. 1.]
 [2. 2. 2. 2.]
 [3. 3. 3. 3.]
 [4. 4. 4. 4.]
 [5. 5. 5. 5.]
 [6. 6. 6. 6.]
 [7. 7. 7. 7.]]


In [99]:
print(arr[[4,3,0,1]])   # return row in particularly given order

[[4. 4. 4. 4.]
 [3. 3. 3. 3.]
 [0. 0. 0. 0.]
 [1. 1. 1. 1.]]


In [101]:
print(arr[[-3,-7,-5]])

[[5. 5. 5. 5.]
 [1. 1. 1. 1.]
 [3. 3. 3. 3.]]


In [102]:
arr = np.arange(32).reshape(8,4)
print(arr)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]]


In [104]:
arr[[1, 5, 7, 2], [0, 3, 1, 2]]   # arr[1][0] , arr[5][3] etc...


array([ 4, 23, 29, 10])

In [105]:
arr = np.arange(20).reshape(4,5)
print(arr)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [106]:
print(arr.T)

[[ 0  5 10 15]
 [ 1  6 11 16]
 [ 2  7 12 17]
 [ 3  8 13 18]
 [ 4  9 14 19]]


In [108]:
print(arr.transpose())

[[ 0  5 10 15]
 [ 1  6 11 16]
 [ 2  7 12 17]
 [ 3  8 13 18]
 [ 4  9 14 19]]


In [113]:
print(arr.swapaxes(0,1))

[[ 0  5 10 15]
 [ 1  6 11 16]
 [ 2  7 12 17]
 [ 3  8 13 18]
 [ 4  9 14 19]]


In [171]:
samp = np.random.standard_normal((3,4))       # Standard Normal Distribution
print(samp)

[[-0.47683468  0.86247371 -1.07202691  1.22460638]
 [-1.18355313  1.58900525 -1.00607499  1.00376832]
 [ 0.12160792 -1.30254048 -0.82470747 -0.28380416]]


In [117]:
randm = np.random.default_rng(seed=123456)
print(randm)
type(randm)

Generator(PCG64)


numpy.random._generator.Generator

In [119]:
arr = np.random.permutation(10)
print(arr)

[7 9 3 2 0 5 6 4 1 8]


In [127]:
arr = np.arange(15)
np.random.shuffle(arr)
print(arr)

[12 11  9 14  8  6 13  4  3  0  5  7 10  1  2]


In [172]:
arr = np.random.uniform(1,5,10)         # Uniform Distribution
print(arr)

[2.15593668 1.42070954 3.76144799 4.69999229 3.17456534 1.66198905
 3.14961349 3.27834428 3.34341908 1.33578416]


In [173]:
n = 10                             # Binomial Distribution
p = 0.3
arr = np.random.binomial(n,p,20)    # output is telling us that out of 10 coin flipping arr[i] will get into success favour
print(arr)

[4 3 4 3 1 2 2 3 4 1 7 2 2 2 2 2 5 4 6 3]


In [196]:
arr = np.random.normal(0,5,10)   # Normal Distribution
print(arr)

mn = np.mean(arr)
sd = np.std(arr)

print(mn)
print(sd)

[-1.21629741 -6.63466163  3.20128058  2.76762753  4.21499275  7.36648995
 -1.44057386  4.44244405  3.19351864  3.69628038]
1.9591100970754396
3.777934624745304


In [175]:
arr = np.random.beta(2,4,10)        # Beta Distribution
print(arr)

[0.42579167 0.4068529  0.41579265 0.57463161 0.20609201 0.27075594
 0.40311715 0.68072729 0.70619269 0.28183429]


In [195]:
arr = np.random.chisquare(3,6)      # Chi-Square Distribution
print(arr)

mn = np.mean(arr)
sd = np.std(arr)

print(mn)
print(sd)

[0.85006045 3.98835047 0.41694723 5.06818156 2.09905787 1.61681254]
2.339901689125258
1.666290234134936


In [194]:
arr = np.random.gamma(2,6,8)        # Gamma Distribution
print(arr)

mn = np.mean(arr)
sd = np.std(arr)

print(mn)
print(sd)

[11.72022717  6.59758667  2.57220935 11.97277761  2.01520292  3.76886851
  6.91469351 18.48809259]
8.006207291973055
5.314469218468004


In [197]:
rng = np.random.default_rng() 
x = rng.standard_normal(1000)
mn = np.mean(x)
sd = np.std(x)

print(mn)
print(sd)

Generator(PCG64)
0.003691256580727231
1.0116796812959756


In [201]:
arr1 = np.random.randint(-10,10,10)
arr2 = np.random.randint(-10,10,10)

maxres = np.maximum(arr1,arr2)
minres = np.minimum(arr1,arr2)
print(arr1)
print(arr2)
print(maxres)
print(minres)

[ -8   7 -10  -9  -3  -6   0   2   2   3]
[ 6  5 -5  1  2  8 -1  7 -3  0]
[ 6  7 -5  1  2  8  0  7  2  3]
[ -8   5 -10  -9  -3  -6  -1   2  -3   0]


In [206]:
arr = np.random.rand(3,2) * 7
print(arr)

[[6.33571979 4.50127923]
 [5.11550151 4.37988671]
 [4.13411687 5.51490959]]


In [208]:
rem,intg = np.modf(arr)    # separates the integer and decimal part

print(rem)
print(intg)

[[0.33571979 0.50127923]
 [0.11550151 0.37988671]
 [0.13411687 0.51490959]]
[[6. 4.]
 [5. 4.]
 [4. 5.]]


In [218]:
arr = np.arange(-5,5,0.1)
print(arr)

[-5.00000000e+00 -4.90000000e+00 -4.80000000e+00 -4.70000000e+00
 -4.60000000e+00 -4.50000000e+00 -4.40000000e+00 -4.30000000e+00
 -4.20000000e+00 -4.10000000e+00 -4.00000000e+00 -3.90000000e+00
 -3.80000000e+00 -3.70000000e+00 -3.60000000e+00 -3.50000000e+00
 -3.40000000e+00 -3.30000000e+00 -3.20000000e+00 -3.10000000e+00
 -3.00000000e+00 -2.90000000e+00 -2.80000000e+00 -2.70000000e+00
 -2.60000000e+00 -2.50000000e+00 -2.40000000e+00 -2.30000000e+00
 -2.20000000e+00 -2.10000000e+00 -2.00000000e+00 -1.90000000e+00
 -1.80000000e+00 -1.70000000e+00 -1.60000000e+00 -1.50000000e+00
 -1.40000000e+00 -1.30000000e+00 -1.20000000e+00 -1.10000000e+00
 -1.00000000e+00 -9.00000000e-01 -8.00000000e-01 -7.00000000e-01
 -6.00000000e-01 -5.00000000e-01 -4.00000000e-01 -3.00000000e-01
 -2.00000000e-01 -1.00000000e-01 -1.77635684e-14  1.00000000e-01
  2.00000000e-01  3.00000000e-01  4.00000000e-01  5.00000000e-01
  6.00000000e-01  7.00000000e-01  8.00000000e-01  9.00000000e-01
  1.00000000e+00  1.10000

In [219]:
xs,ys = np.meshgrid(arr,arr)

print(xs)
# print(ys)

[[-5.  -4.9 -4.8 ...  4.7  4.8  4.9]
 [-5.  -4.9 -4.8 ...  4.7  4.8  4.9]
 [-5.  -4.9 -4.8 ...  4.7  4.8  4.9]
 ...
 [-5.  -4.9 -4.8 ...  4.7  4.8  4.9]
 [-5.  -4.9 -4.8 ...  4.7  4.8  4.9]
 [-5.  -4.9 -4.8 ...  4.7  4.8  4.9]]


In [220]:
print(ys)

[[-5.  -5.  -5.  ... -5.  -5.  -5. ]
 [-4.9 -4.9 -4.9 ... -4.9 -4.9 -4.9]
 [-4.8 -4.8 -4.8 ... -4.8 -4.8 -4.8]
 ...
 [ 4.7  4.7  4.7 ...  4.7  4.7  4.7]
 [ 4.8  4.8  4.8 ...  4.8  4.8  4.8]
 [ 4.9  4.9  4.9 ...  4.9  4.9  4.9]]


In [221]:
z = np.sqrt(xs**2 + ys**2)
print(z)

[[7.07106781 7.00071425 6.93108938 ... 6.86221539 6.93108938 7.00071425]
 [7.00071425 6.92964646 6.85930026 ... 6.78969808 6.85930026 6.92964646]
 [6.93108938 6.85930026 6.7882251  ... 6.71788657 6.7882251  6.85930026]
 ...
 [6.86221539 6.78969808 6.71788657 ... 6.64680374 6.71788657 6.78969808]
 [6.93108938 6.85930026 6.7882251  ... 6.71788657 6.7882251  6.85930026]
 [7.00071425 6.92964646 6.85930026 ... 6.78969808 6.85930026 6.92964646]]


In [232]:
xarr = np.array([1.1, 1.2, 1.3, 1.4, 1.5])
yarr = np.array([2.1, 2.2, 2.3, 2.4, 2.5])

cond = np.array([True, False, True, True, False])

res = np.where(cond,xarr,yarr)     # Take element from xarr when cond is true else take from yarr
print(res)

[1.1 2.2 1.3 1.4 2.5]


In [239]:
arr = rng.standard_normal((4, 4))

arr[(3,2)] = 0
print(arr)
# print(arr>0)

[[ 2.42704094 -0.33556598  1.53484647  2.19818534]
 [-0.75728119 -0.19554158 -0.43714847  0.58118209]
 [-0.59037599  1.58898864  1.63052544  0.6369538 ]
 [ 0.19283773 -0.13238036  0.         -0.21261966]]


In [238]:
res = np.where(arr>0 , 2 , -2)    # if element is +ve then replace with 2 otherwise with -2 

print(res)

[[ 2 -2 -2  2]
 [ 2  2  2  2]
 [ 2  2  2 -2]
 [ 2  2 -2  2]]


In [241]:
arr = np.array([5,3,7,9,4,0,2])

print(arr.argmin())
print(arr.argmax())

5
3


In [248]:
arr = np.random.randint(-100,100,20)
print(arr)

[-43  83  89  48 -63  68  66  31 -12  26  86  73 -63  62  13  61 -98  21
  23 -22]


In [245]:
print(arr.argmin())
print(arr.argmax())

15
11


In [250]:
print((arr>0).sum())   # Number of positive numbers
print((arr<=0).sum())  # Number of negative numbers

14
6


In [260]:
arr = np.random.randint(-10,10,10)

print(arr)
bools = arr > 0
print(bools)

print(bools.any())    # If atleast one true comes in bool array return true
print(bools.all())    # If all element in bool array is true then return true

[-4  5  8  0  4 -8 -7  3  9  8]
[False  True  True False  True False False  True  True  True]
True
False


In [263]:
arr = np.random.randint(-2,2,10)

print(arr)

[ 1  1  0 -2 -1  0  0 -2  0  1]


In [264]:
uni = np.unique(arr)
print(uni)

[-2 -1  0  1]


In [265]:
type(uni)

numpy.ndarray

In [268]:
values = np.array([6, 0, 0, 3, 2, 5, 6])

isPresent = np.isin(values , [2,3,6])    # Check if 2/3/6 present in array or not 

print(isPresent)

[ True False False  True  True False  True]


In [269]:
arr = np.arange(10)

np.save("some_array", arr)

In [270]:
 np.load("some_array.npy")

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [285]:
arr = np.ones(3)
print(arr)
print(arr.shape)

[1. 1. 1.]
(3,)


In [283]:
x = np.array([[1., 2., 3.], [4., 5., 6.]])

mul = x @ arr
print(mul)

[ 6. 15.]
