# GPT Generated NumPy Operation Question 


## Easy Difficulty

In [2]:
import numpy as np

In [3]:
data = np.array([
    [85, 78, 92],
    [88, 76, 95],
    [90, 85, 91],
    [70, 60, 65]
])

- 👉 Tasks:

- Extract marks of the 2nd student
- Extract all marks of the 3rd subject
- Find total marks per student

In [4]:
st2 = data[1:2,:]
print(st2)

[[88 76 95]]


In [5]:
st3 = data[2:3,:]
print(st3)

[[90 85 91]]


In [6]:
marks = np.sum(data,axis = 1)
print(marks)

[255 259 266 195]


- 👉 Task:

- Identify students whose average score is less than 75

In [8]:
avgg = np.average(data,axis = 1)
print(avgg)
a = data[avgg > 75]
print(a)

[85.         86.33333333 88.66666667 65.        ]
[[85 78 92]
 [88 76 95]
 [90 85 91]]


- Add 5 bonus marks to all students.

👉 Constraint:

- Use broadcasting (no loops)

In [9]:
upd_marks = marks + 5
print(upd_marks)

[260 264 271 200]


- 👉 Tasks:

- Find mean score of each subject
- Find max score per subject

In [10]:
mn = np.mean(data , axis = 0)
print(mn)

[83.25 74.75 85.75]


In [11]:
mx = np.max(data , axis = 0)
print(mx)

[90 85 95]


- Normalize the dataset between 0 and 1 using: Formula (x-xmin)/(xmax-xmin)

In [12]:
normalized_dataset = (data - np.min(data)) / (np.max(data) - np.min(data))

print(normalized_dataset)

[[0.71428571 0.51428571 0.91428571]
 [0.8        0.45714286 1.        ]
 [0.85714286 0.71428571 0.88571429]
 [0.28571429 0.         0.14285714]]


- 👉 Task:
- Create a boolean array where marks ≥ 75 are True.
- Replace all marks less than 70 with 70.

In [20]:
bools = data>75
upArr = np.where(~bools , 70 , data)

print(bools)
print(upArr)

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]
 [False False False]]
[[85 78 92]
 [88 76 95]
 [90 85 91]
 [70 70 70]]


### Another dataset

In [13]:
arr = np.arange(24)

- 👉 Tasks:

- Convert into shape (6, 4)
- Convert into shape (2, 3, 4)

In [16]:
arr1 = np.reshape(arr,(6,4))
arr2 = np.reshape(arr,(2,3,4))

print(arr1)
print(arr2)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


- 👉 Task:
- Generate a dataset of 5 students and 3 subjects with marks between 50–100.

In [52]:
dataset = np.random.randint(50,100,(5,3))
print(dataset)

[[85 91 58]
 [77 83 78]
 [84 88 74]
 [75 93 92]
 [77 86 52]]


👉 Task:
- Create a new column for average marks per student and append it to dataset.

In [53]:
col = np.average(dataset , axis = 1,keepdims = True)
print("\n")
print(col)



[[78.        ]
 [79.33333333]
 [82.        ]
 [86.66666667]
 [71.66666667]]


In [64]:
new_data = np.concatenate((dataset , col),axis = 1)

     # OR

new_data1 = np.hstack((dataset,col))

print(new_data1)

[[85.         91.         58.         78.        ]
 [77.         83.         78.         79.33333333]
 [84.         88.         74.         82.        ]
 [75.         93.         92.         86.66666667]
 [77.         86.         52.         71.66666667]]


#### New dataset 

In [3]:
data = np.array([
    [85, np.nan, 92],
    [88, 76, np.nan],
    [np.nan, 85, 91]
])

- 👉 Task:

Replace NaN with column-wise mean

In [10]:
col_mean = np.nanmean(data,axis = 0)
idx = np.where(np.isnan(data))
data[idx] = np.take(col_mean,idx[1])

print(idx)

print(data)

(array([], dtype=int64), array([], dtype=int64))
[[85.  80.5 92. ]
 [88.  76.  91.5]
 [86.5 85.  91. ]]


- Standardize each feature using:

In [11]:
std_data = (data - np.mean(data)) / np.std(data)

print(std_data)

[[-0.23204774 -1.12708903  1.1602387 ]
 [ 0.36464645 -2.02213031  1.06078967]
 [ 0.06629935 -0.23204774  0.96134064]]


👉 Task:

- Find values greater than mean + 2*std
- Replace them with mean

In [16]:
cond = np.mean(data) +  np.std(data)
print(cond)
new_data = np.where(data > cond,np.mean(data),data)
print(new_data)

91.19436770966612
[[85.         80.5        86.16666667]
 [88.         76.         86.16666667]
 [86.5        85.         91.        ]]


In [17]:
data = np.array([
    [85, 78, 92],
    [88, 76, 95],
    [90, 85, 91],
    [70, 60, 65]
])

In [21]:
import numpy as np
row_mean = np.mean(data, axis=1, keepdims=True)
row_std = np.std(data, axis=1, keepdims=True)
print(row_mean)
print(row_std)
normalized_data = (data - row_mean) / row_std

print(normalized_data)

[[85.        ]
 [86.33333333]
 [88.66666667]
 [65.        ]]
[[5.71547607]
 [7.84573486]
 [2.62466929]
 [4.0824829 ]]
[[ 0.         -1.22474487  1.22474487]
 [ 0.21242964 -1.31706379  1.10463415]
 [ 0.50800051 -1.3970014   0.88900089]
 [ 1.22474487 -1.22474487  0.        ]]
