# Dataset 1

In [19]:
import numpy as np

np.random.seed(42)

n = 120  # number of rows

order_id = np.arange(1000, 1000 + n)

customer_id = np.random.randint(100, 200, size=n)

product_category = np.random.choice([0, 1, 2, 3], size=n, p=[0.3, 0.3, 0.2, 0.2])

price = np.round(np.random.uniform(200, 5000, size=n), 2)

quantity = np.random.randint(1, 6, size=n)

discount = np.round(np.random.choice([0, 0.1, 0.2, 0.3, 0.5],size=n,p=[0.4, 0.2, 0.2, 0.1, 0.1]), 2)

rating = np.random.randint(1, 6, size=n)

delivery_days = np.random.randint(1, 10, size=n)

is_returned = (rating <= 2).astype(int)

# Final dataset
data = np.column_stack((
    order_id,
    customer_id,
    product_category,
    price,
    quantity,
    discount,
    rating,
    delivery_days,
    is_returned
))

print(data.shape)  # (120, 9)

(120, 9)


In [17]:
print(data)

[[1.000e+03 1.510e+02 2.000e+00 ... 2.000e+00 1.000e+00 1.000e+00]
 [1.001e+03 1.920e+02 2.000e+00 ... 1.000e+00 8.000e+00 1.000e+00]
 [1.002e+03 1.140e+02 3.000e+00 ... 3.000e+00 1.000e+00 0.000e+00]
 ...
 [1.117e+03 1.800e+02 3.000e+00 ... 1.000e+00 5.000e+00 1.000e+00]
 [1.118e+03 1.070e+02 0.000e+00 ... 2.000e+00 2.000e+00 1.000e+00]
 [1.119e+03 1.340e+02 0.000e+00 ... 4.000e+00 5.000e+00 0.000e+00]]


🔹 Medium Level (Warm-up)
Q1. High Value Orders

Find all orders where total purchase value (price × quantity) is greater than ₹10,000.

Hint:
Create a new array for total value → use boolean masking.

Q2. Electronics Performance

For Electronics category (0), compute:

Average rating
Average delivery days

Hint:
Filter rows first → then apply aggregation functions.

In [12]:
# Q1
total_value = data[data[:, 3] * data[:, 4] > 10000]
print(total_value)

# Q2
elec = data[data[:, 2] == 0]

avg_rating = elec[:, 6].mean()
print(avg_rating)

avg_days = elec[:, 7].mean()
print(avg_days)

[[1.00000e+03 1.51000e+02 2.00000e+00 3.56172e+03 4.00000e+00 0.00000e+00
  4.00000e+00 3.00000e+00 0.00000e+00]
 [1.00100e+03 1.92000e+02 2.00000e+00 4.26397e+03 5.00000e+00 0.00000e+00
  2.00000e+00 9.00000e+00 1.00000e+00]
 [1.00800e+03 1.74000e+02 1.00000e+00 3.41114e+03 5.00000e+00 0.00000e+00
  1.00000e+00 4.00000e+00 1.00000e+00]
 [1.00900e+03 1.74000e+02 2.00000e+00 2.98730e+03 5.00000e+00 0.00000e+00
  4.00000e+00 8.00000e+00 0.00000e+00]
 [1.01100e+03 1.99000e+02 1.00000e+00 4.71264e+03 5.00000e+00 0.00000e+00
  1.00000e+00 3.00000e+00 1.00000e+00]
 [1.01200e+03 1.23000e+02 0.00000e+00 4.87359e+03 5.00000e+00 0.00000e+00
  1.00000e+00 3.00000e+00 1.00000e+00]
 [1.01500e+03 1.52000e+02 3.00000e+00 2.53095e+03 4.00000e+00 0.00000e+00
  4.00000e+00 3.00000e+00 0.00000e+00]
 [1.01700e+03 1.87000e+02 2.00000e+00 4.97340e+03 3.00000e+00 0.00000e+00
  4.00000e+00 5.00000e+00 0.00000e+00]
 [1.02000e+03 1.01000e+02 0.00000e+00 2.57069e+03 5.00000e+00 0.00000e+00
  3.00000e+00 5.00000e

- 🔸 Medium-Hard Level
Q3. Discount Impact Analysis

Compare average total purchase value for:

Orders with discount ≥ 20%
Orders with no discount

Hint:
Split dataset using boolean masks → compute separately.

Q4. Customer Purchase Frequency

Find the top 5 customers who made the highest number of purchases.

Hint:
Use np.unique(..., return_counts=True).

Q5. Category-wise Revenue

Calculate total revenue generated by each product category.

Hint:
Loop OR use masking per category → multiply price × quantity.

Q6. Return Behavior Analysis

Check if low ratings actually lead to returns:

Compare return rate for ratings ≤ 2 vs > 2

Hint:
Use conditional masks and compute ratios.

In [22]:
disc = data[data[:,5] >= 0.2]
print(disc)

[[1.00000e+03 1.51000e+02 2.00000e+00 3.56172e+03 4.00000e+00 3.00000e-01
  2.00000e+00 1.00000e+00 1.00000e+00]
 [1.00300e+03 1.71000e+02 2.00000e+00 2.14164e+03 2.00000e+00 5.00000e-01
  1.00000e+00 3.00000e+00 1.00000e+00]
 [1.00600e+03 1.82000e+02 1.00000e+00 4.69105e+03 2.00000e+00 5.00000e-01
  1.00000e+00 6.00000e+00 1.00000e+00]
 [1.00700e+03 1.86000e+02 0.00000e+00 3.96964e+03 1.00000e+00 5.00000e-01
  5.00000e+00 7.00000e+00 0.00000e+00]
 [1.00900e+03 1.74000e+02 2.00000e+00 2.98730e+03 5.00000e+00 2.00000e-01
  3.00000e+00 2.00000e+00 0.00000e+00]
 [1.01300e+03 1.02000e+02 1.00000e+00 1.56282e+03 5.00000e+00 2.00000e-01
  5.00000e+00 3.00000e+00 0.00000e+00]
 [1.01400e+03 1.21000e+02 1.00000e+00 1.66575e+03 3.00000e+00 2.00000e-01
  2.00000e+00 7.00000e+00 1.00000e+00]
 [1.01500e+03 1.52000e+02 3.00000e+00 2.53095e+03 4.00000e+00 2.00000e-01
  2.00000e+00 2.00000e+00 1.00000e+00]
 [1.01600e+03 1.01000e+02 3.00000e+00 2.35244e+03 2.00000e+00 2.00000e-01
  3.00000e+00 6.00000e

In [24]:
nodisc = data[data[:,5] == 0]
print(nodisc)

[[1.00100e+03 1.92000e+02 2.00000e+00 4.26397e+03 5.00000e+00 0.00000e+00
  1.00000e+00 8.00000e+00 1.00000e+00]
 [1.00200e+03 1.14000e+02 3.00000e+00 4.31036e+03 1.00000e+00 0.00000e+00
  3.00000e+00 1.00000e+00 0.00000e+00]
 [1.00400e+03 1.60000e+02 3.00000e+00 4.46130e+03 2.00000e+00 0.00000e+00
  5.00000e+00 4.00000e+00 0.00000e+00]
 [1.00500e+03 1.20000e+02 3.00000e+00 4.28446e+03 1.00000e+00 0.00000e+00
  4.00000e+00 8.00000e+00 0.00000e+00]
 [1.01100e+03 1.99000e+02 1.00000e+00 4.71264e+03 5.00000e+00 0.00000e+00
  5.00000e+00 3.00000e+00 0.00000e+00]
 [1.01200e+03 1.23000e+02 0.00000e+00 4.87359e+03 5.00000e+00 0.00000e+00
  5.00000e+00 7.00000e+00 0.00000e+00]
 [1.01700e+03 1.87000e+02 2.00000e+00 4.97340e+03 3.00000e+00 0.00000e+00
  1.00000e+00 3.00000e+00 1.00000e+00]
 [1.01900e+03 1.37000e+02 0.00000e+00 2.86760e+02 1.00000e+00 0.00000e+00
  1.00000e+00 9.00000e+00 1.00000e+00]
 [1.02300e+03 1.20000e+02 1.00000e+00 3.77202e+03 1.00000e+00 0.00000e+00
  5.00000e+00 9.00000e

In [ ]:
ttl_valdisc = (disc[:,3] * disc[:,4]).mean()
print(ttl_valdisc)

ttl_valnodisc = (nodisc[:,3] * nodisc[:,4]).mean()
print(ttl_valnodisc)

In [48]:
cust , count = np.unique(data[:,1] , return_counts=True)      # Return array and count number

idx = np.argsort(count)

print(idx)

top_five = idx[-5:]
print(top_five)

[ 0 24 25 26 51 28 30 31 23 32 34 49 48 37 38 39 41 66 22 21 57 63  4  5
  8 58 19 56 45 15 16 17 18 55 50 54 53 59 62 46 64 47 65 52 33 43  2  7
  9 44 13 14 11 27 29 36 20 67 12 35  6  3 10 60 61  1 40 42]
[60 61  1 40 42]


In [47]:
top_customers = cust[top_five]
top_counts = count[top_five]

print(top_customers)
print(top_counts)

[187. 188. 101. 159. 161.]
[4 4 4 5 5]


In [71]:
arr = data[:,2]

cat = np.unique(arr)
res = []

for c in cat:
    ele = data[data[:,2] == c]
    ttl_rev = (ele[:,3] * ele[:,4])
    summ = ttl_rev.sum()
    res.append(summ)

type(res)
ans = np.array(res)
print(ans)

[282293.77 283111.12 202747.91 169032.67]
